services:
  frontend:
    container_name: assistant-frontend
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    image: assistant-frontend:latest
    ports:
      - "4000:80"
    depends_on:
      - backend-server
  backend-server:
    container_name: assistant-backend
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    image: assistant-backend:latest
    ports:
      - "8080:8080"
    environment:
      - OPENWEBUI_BASE_URL=${OPENWEBUI_BASE_URL}
      - OPENWEBUI_API_KEY=${OPENWEBUI_API_KEY}
      - OPENWEBUI_MODEL_NAME=${OPENWEBUI_MODEL_NAME}
      - AUTOMATIC1111_BASE_URL=${AUTOMATIC1111_BASE_URL}
      - AUTOMATIC1111_MODEL_NAME=${AUTOMATIC1111_MODEL_NAME}
      - WEATHER_BASE_URL=${WEATHER_BASE_URL}
      - WEATHER_API_KEY=${WEATHER_API_KEY}
      - NEWS_BASE_URL=${NEWS_BASE_URL}
      - NEWS_API_KEY=${NEWS_API_KEY}
      - CALENDAR_BASE_URL=${CALENDAR_BASE_URL}
      - CALENDAR_API_KEY=${CALENDAR_API_KEY}