services:
  frontend:
    container_name: assistant-frontend
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    image: assistant-frontend:latest
    ports:
      - "4000:80"
    depends_on:
      - backend-server
  backend-server:
    container_name: assistant-backend
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    image: assistant-backend:latest
    ports:
      - "8080:8080"
    environment:
      - OLLAMA_BASE_URL=${OLLAMA_BASE_URL}
      - OLLAMA_API_KEY=${OLLAMA_API_KEY}
      - OLLAMA_MODEL_NAME=${OLLAMA_MODEL_NAME}
